version: '3.3'

services:
  traefik:
    image: traefik
    labels:
      - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)'
      - 'traefik.http.routers.http-catchall.entrypoints=web'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

      - 'traefik.http.routers.dashboard.rule=Host(`pico.test`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls=true'
      - 'traefik.http.routers.dashboard.service=dashboard'
      - 'traefik.http.services.dashboard.loadbalancer.server.port=8080'
    ports:
      - '22:22'
      - '80:80'
      - '443:443'
      - '6379:6379'
      - '3306:3306'
      - '5432:5432'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/config
      - ./letsencrypt:/letsencrypt
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ~/.local/certs/:/certs/
    restart: always
  whoami:
    image: containous/whoami
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`whoami.pico.test`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls=true'
    restart: always
  gitea:
    image: gitea/gitea
    hostname: git.pico.test
    labels:
      - 'traefik.http.routers.gitea-web.rule=Host(`git.pico.test`)'
      - 'traefik.http.routers.gitea-web.tls=true'
      - 'traefik.http.services.gitea-web.loadbalancer.server.port=3000'

      - 'traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.gitea-ssh.entrypoints=ssh'
      - 'traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22'
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  mailhog:
    image: mailhog/mailhog
    hostname: mail.pico.test
    labels:
      - 'traefik.http.routers.mailhog.rule=Host(`mail.pico.test`)'
      - 'traefik.http.routers.mailhog.tls=true'
      - 'traefik.http.routers.mailhog.entrypoints=websecure'
      - 'traefik.http.routers.mailhog.service=mailhog'
      - 'traefik.http.services.mailhog.loadbalancer.server.port=8025'
    logging:
      driver: 'none' # disable saving logs
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.250
    # ports:
    #   - 1025:1025 # smtp server
    #   - 8025:8025 # web ui
networks:
  default:
    external:
      name: picobug
