version: '3.3'

services:
  traefik:
    image: traefik
    hostname: pico.test
    labels:
      - 'traefik.http.routers.dashboard.rule=Host(`pico.test`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls=true'
      - 'traefik.http.routers.dashboard.service=api@internal'
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
      - '6379:6379'
      - '3306:3306'
      - '5432:5432'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/config
      - ./letsencrypt:/letsencrypt
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ~/.local/certs/:/certs/
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.252
  whoami:
    image: traefik/whoami
    hostname: whoami.pico.test
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`whoami.pico.test`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls=true'
    restart: always
  gitea:
    image: gitea/gitea
    hostname: git.pico.test
    labels:
      - 'traefik.http.routers.gitea-web.rule=Host(`git.pico.test`)'
      - 'traefik.http.routers.gitea-web.tls=true'
      - 'traefik.http.services.gitea-web.loadbalancer.server.port=3000'

      - 'traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.gitea-ssh.entrypoints=ssh'
      - 'traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22'
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  mailhog:
    image: axllent/mailpit
    # image: druidfi/mailhog
    hostname: mail.pico.test
    labels:
      - 'traefik.http.routers.mailhog.rule=Host(`mail.pico.test`)'
      - 'traefik.http.routers.mailhog.tls=true'
      - 'traefik.http.routers.mailhog.entrypoints=websecure'
      - 'traefik.http.routers.mailhog.service=mailhog'
      - 'traefik.http.services.mailhog.loadbalancer.server.port=8025'
    logging:
      driver: 'none' # disable saving logs
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.250
    # ports:
    #   - 1025:1025 # smtp server
    #   - 8025:8025 # web ui
  openssh:
    image: lscr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server #optional
    labels:
      - 'traefik.tcp.routers.openssh.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.openssh.entrypoints=openssh'
      - 'traefik.tcp.routers.openssh.service=openssh-proxy'
      - 'traefik.tcp.services.openssh-proxy.loadbalancer.server.port=2222'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PUBLIC_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEGHgRoVmhCfxKavNOB4pfNynT+YuD9KsGOdSzCZTyc Picobug SSH #optional
      # - PUBLIC_KEY_FILE=/path/to/file #optional
      # - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      # - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=false #optional
      - USER_PASSWORD=picossh #optional
      # - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=picobug #optional
    volumes:
      - ./letsencrypt/sshconfig:/config
    # ports:
    #  - 2222:2222
    restart: unless-stopped
  mariadb:
    image: jbergstroem/mariadb-alpine
    labels:
      - 'traefik.tcp.routers.legacydb.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.legacydb.entrypoints=mariadb'
      - 'traefik.tcp.routers.legacydb.service=legacydb-proxy'
      - 'traefik.tcp.services.legacydb-proxy.loadbalancer.server.port=3306'
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: julio_pico
      MYSQL_USER: "${USER}"
      MYSQL_PASSWORD: "${PASS}"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    restart: always
  redis:
    image: redis:alpine
    ulimits:
      memlock: -1
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.redis.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.redis.entrypoints=redis'
      - 'traefik.tcp.routers.redis.service=redis-proxy'
      - 'traefik.tcp.services.redis-proxy.loadbalancer.server.port=6379'
    volumes:
      - redis:/data
    command: redis-server --maxmemory 32mb --appendonly no --maxmemory-policy allkeys-lru
    restart: always
  minio:
    image: 'minio/minio'
    labels:
      - 'traefik.http.routers.minio.rule=Host(`minio.pico.test`)'
      - 'traefik.http.routers.minio.tls=true'
      - 'traefik.http.routers.minio.entrypoints=websecure'
      - 'traefik.http.routers.minio.service=minio'
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'

      - 'traefik.http.routers.cminio.rule=Host(`cminio.pico.test`)'
      - 'traefik.http.routers.cminio.tls=true'
      - 'traefik.http.routers.cminio.entrypoints=websecure'
      - 'traefik.http.routers.cminio.service=cminio'
      - 'traefik.http.services.cminio.loadbalancer.server.port=8900'
    env_file:
      - .env
    volumes:
        - 'minio:/data'
    restart: unless-stopped
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        retries: 3
        timeout: 5s
    extra_hosts:
      - "minio.pico.test:172.16.1.252"
    networks:
      default:
        ipv4_address: 172.16.1.253
volumes:
  mariadb:
    driver: 'local'
  redis:
    driver: 'local'
  minio:
    driver: 'local'
networks:
  default:
    external: true
    name: picobug
